language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  
matrix:
  allow_failures:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: hhvm
  fast_finish: true
